COUNTRY_MAP = {
    # Europa
    "albania": "96",
    "andorra": "97",
    "armenia": "98",
    "austria": "99",
    "azerbaijan": "100",
    "belarus": "101",
    "belgium": "5",
    "bosnia and herzegovina": "102",
    "bulgaria": "103",
    "croatia": "104",
    "cyprus": "105",
    "czechia": "106",
    "denmark": "107",
    "england": "11",
    "estonia": "108",
    "faroe islands": "109",
    "finland": "110",
    "france": "6",
    "georgia": "111",
    "germany": "7",
    "gibraltar": "112",
    "greece": "12",
    "guernsey": "113",
    "holy see": "114",
    "hungary": "115",
    "iceland": "116",
    "isle of man": "117",
    "italy": "8",
    "jersey": "118",
    "kazakhstan": "119",
    "kosovo": "120",
    "latvia": "121",
    "liechtenstein": "122",
    "lithuania": "123",
    "luxembourg": "124",
    "malta": "125",
    "moldova": "126",
    "monaco": "127",
    "montenegro": "128",
    "netherlands": "15",
    "north macedonia": "129",
    "northern ireland": "130",
    "norway": "131",
    "poland": "132",
    "portugal": "13",
    "romania": "133",
    "russia": "134",
    "san marino": "135",
    "scotland": "14",
    "serbia": "136",
    "slovakia": "137",
    "slovenia": "138",
    "spain": "1",
    "sweden": "139",
    "switzerland": "16",
    "turkey": "17",
    "ukraine": "140",
    "wales": "18",
    "åland islands": "141",

    # South America
    "argentina": "20",
    "bolivia": "21",
    "brazil": "22",
    "chile": "23",
    "colombia": "24",
    "ecuador": "25",
    "falkland islands (malvinas)": "26",
    "french guiana": "27",
    "guyana": "28",
    "paraguay": "29",
    "peru": "30",
    "suriname": "31",
    "uruguay": "32",
    "venezuela": "33",

    # North America
    "anguilla": "34",
    "antigua and barbuda": "35",
    "aruba": "36",
    "bahamas": "37",
    "barbados": "38",
    "belize": "39",
    "bermuda": "40",
    "bonaire": "41",
    "canada": "42",
    "cayman islands": "43",
    "costa rica": "44",
    "cuba": "45",
    "curacao": "46",
    "dominica": "47",
    "dominican republic": "48",
    "el salvador": "49",
    "greenland": "50",
    "grenada": "51",
    "guadeloupe": "52",
    "guatemala": "78",
    "haiti": "79",
    "honduras": "80",
    "jamaica": "81",
    "martinique": "82",
    "mexico": "83",
    "montserrat": "84",
    "nicaragua": "85",
    "panama": "86",
    "puerto rico": "87",
    "saint barthélemy": "88",
    "saint kitts and nevis": "89",
    "saint lucia": "90",
    "saint martin (french part)": "91",
    "saint pierre and miquelon": "92",
    "saint vincent and the grenadines": "93",
    "sint maarten (dutch part)": "94",
    "trinidad and tobago": "95",
    "united states": "54",
    "virgin islands, british": "142",
    "virgin islands, u.s.": "143",

    # Africa
    "algeria": "55",
    "angola": "56",
    "benin": "57",
    "botswana": "58",
    "burkina faso": "59",
    "burundi": "60",
    "cabo verde": "61",
    "cameroon": "62",
    "central african republic": "63",
    "chad": "64",
    "comoros": "65",
    "congo": "66",
    "congo dr": "67",
    "côte d'ivoire": "68",
    "djibouti": "69",
    "egypt": "70",
    "equatorial guinea": "71",
    "eritrea": "72",
    "eswatini": "73",
    "ethiopia": "74",
    "gabon": "75",
    "gambia": "76",
    "ghana": "77",
    "guinea": "78",
    "guinea-bissau": "79",
    "kenya": "80",
    "lesotho": "81",
    "liberia": "82",
    "libya": "83",
    "madagascar": "84",
    "malawi": "85",
    "mali": "86",
    "mauritania": "87",
    "mauritius": "88",
    "mayotte": "89",
    "morocco": "90",
    "mozambique": "91",
    "namibia": "92",
    "niger": "93",
    "nigeria": "94",
    "réunion": "95",
    "rwanda": "96",
    "saint helena, ascension and tristan da cunha": "97",
    "senegal": "98",
    "seychelles": "99",
    "sierra leone": "100",
    "somalia": "101",
    "south africa": "102",
    "south sudan": "103",
    "sudan": "104",
    "são tomé and príncipe": "105",
    "tanzania": "106",
    "togo": "107",
    "tunisia": "108",
    "uganda": "109",
    "western sahara": "110",
    "zambia": "111",
    "zimbabwe": "112",

    # Asia
    "afghanistan": "144",
    "bahrain": "145",
    "bangladesh": "146",
    "bhutan": "147",
    "brunei darussalam": "148",
    "cambodia": "149",
    "china pr": "150",
    "india": "151",
    "indonesia": "152",
    "iran": "153",
    "iraq": "154",
    "israel": "155",
    "japan": "156",
    "jordan": "157",
    "kazakhstan": "119",
    "kuwait": "158",
    "kyrgyzstan": "159",
    "laos": "160",
    "lebanon": "161",
    "macau": "162",
    "malaysia": "163",
    "maldives": "164",
    "mongolia": "165",
    "myanmar": "166",
    "nepal": "167",
    "oman": "168",
    "pakistan": "169",
    "palestine": "170",
    "philippines": "171",
    "qatar": "172",
    "saudi arabia": "173",
    "singapore": "174",
    "south korea": "175",
    "sri lanka": "176",
    "syria": "177",
    "tajikistan": "178",
    "thailand": "179",
    "timor-leste": "180",
    "turkmenistan": "181",
    "united arab emirates": "182",
    "uzbekistan": "183",
    "vietnam": "184",
    "yemen": "185",

    # Oceania
    "american samoa": "186",
    "australia": "187",
    "cook islands": "188",
    "federated states of micronesia": "189",
    "fiji": "190",
    "france": "191",
    "guam": "192",
    "kiribati": "193",
    "marshall islands": "194",
    "nauru": "195",
    "new caledonia": "196",
    "new zealand": "197",
    "niue": "198",
    "norfolk island": "199",
    "northern mariana islands": "200",
    "palau": "201",
    "papua new guinea": "202",
    "pitcairn": "203",
    "samoa": "204",
    "solomon islands": "205",
    "tokelau": "206",
    "tonga": "207",
    "tuvalu": "208",
    "vanuatu": "209",
    "wallis and futuna": "210",

    # Antartica
    "antarctica": "211",
    "bouvet island": "212",
    "french southern territories": "213",
    "heard island and mcdonald islands": "214",
    "south georgia and the south sandwich islands": "215"
}

PREFERRED_FOOT = {
    "right": "1",
    "left": "2"
}